Try to fix mysql connection error

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -63,21 +63,30 @@ jobs:
       - name: Build Docker images (test)
         run: docker compose -f docker-compose.prod.yaml build
 
+      - name: List docker images 
+        run: docker images
+
       # 8. Start containers
       - name: Start containers
-        run: docker compose -f docker-compose.prod.yaml up -d
+        run: docker compose -f docker-compose.prod.yaml up -d 
+
+      - name: List containers
+        run: docker ps -a
 
       # 9. Wait for MySQL to be ready
-      - name: Wait for MySQL to be ready
+      - name: Wait for MySQL
         run: |
-          echo "Waiting for MySQL..."
-
-          until docker exec db mysqladmin ping -h "localhost" --silent; do
-            echo "MySQL is not ready yet..."
+          for i in {1..30}; do
+            if docker exec db mysqladmin ping -h "localhost" -uroot -p${{ secrets.DB_PASSWORD }} --silent; then
+              echo "MySQL is ready!"
+              exit 0
+            fi
             sleep 2
           done
 
-          echo "MySQL is ready!"
+          echo "MySQL failed"
+          docker logs db
+          exit 1
 
       # 10. Run migrations inside container
       - name: Run Migrations
